### ISSUE TITLE
Subdirectory site install

### ISSUE THREAD

**Issue by 4alldigital** [platformsh/platformsh-cli#411]
When having my Drupal install ins a subdirectory (../public/sitename/) the symlinks don't work, so I have to use the --copy flag. This isn't great for a dev process as I can't work on the code base in the repo.  I think the symlinks should be more dynamic, rather than hard coded to ../../../../repository

not sure if is an issue or feature request...

**Comment by pjcdawkins** [comment]
The symlinks aren't hard-coded. What does your repository file structure look like?

**Comment by 4alldigital** [comment]
Sorry I thought they were.

repo structure is, as normal:
/modules
/themes
.platform.app.yaml

build hook we came up with to get working was as follows:

```
build: |
      # The subpath directory should exist already because it was created via
      # the public files mount.
      mkdir -p public/sitename
      mv public/* public/sitename/ 2>/dev/null || true
      mv public/sites/* public/sitename/sites/ 2>/dev/null || true
      mv public/sites/default/* public/sitename/sites/default/ 2>/dev/null || true
      rmdir public/sites/default
      rmdir public/sites
      cd public/sitename/sites/default/
      if [ ! $PLATFORM_ENVIRONMENT ]; then
      # If local
      ln -s ../../../../../../shared/settings.local.php
      cd ../../../../
      cd public/sitename/profiles/dataproducts/themes/custom/the_dataproducts
      fi
      npm install
      bower install
      npm rebuild node-sass
      gulp sass:prod
```

**Comment by pjcdawkins** [comment]
OK... the symlinks are created before the build hooks run, so that's why you get the wrong path if you're moving stuff around in the build hooks.

The `--abslinks` option lets you use absolute paths for the symlinks, but I guess you've already explored that option.

Hm...

**Comment by 4alldigital** [comment]
the absolute links don't work because of the docker (or any host->guest) dev environment with the repo paths on the host volume mapped on the guest being different.

If you feel this is an edge case scenario you think that won't ever occur again, feel free to leave it/close it.  But thought it worth highlighting.

**Comment by pjcdawkins** [comment]
It might be less complicated to remove Platform.sh's Drupal processes, and build Drupal yourself, something like:

```yaml
# don't build as Drupal automatically
build:
  flavor: composer

hooks:
  build: |
      # Build the Drupal profile using Drush Make.
      mkdir -p public
      drush make project-core.make public/sitename --yes --concurrency=4 --cache-duration-releasexml=300
      drush make project.make public/sitename/profiles/profilename --no-core -contrib-destination=. --cache-duration-releasexml=300' --concurrency=4
      mv * public/sitename/profiles/profilename/
```

... you'd also need to add Platform.sh database settings to settings.php, etc. - quite a lot of work, but it might end up cleaner than undoing the work that Platform.sh did automagically.
