### ISSUE TITLE
CLI not respecting default_schema

### ISSUE THREAD

**Issue by galister** [platformsh/platformsh-cli#635]
It looks like when a relationship has access to multiple schemas, Platform CLI doesn't respect the default_schema field.
```
platform db:sql -vvv -r second_db -p xxxxxxxxxxxx -e multi-db-branch "SHOW TABLES;"
```
translates to:
```
mysql --no-auto-rehash '--user=admin' '--password=xxxxxxxxxxxx' '--host=second_db.internal' --port=3306 'main' --execute 'SHOW TABLES;'
```
even though
```
      second:
        default_schema: second_sb
        privileges:
          second_sb: admin
```
```
relationships:
  database: 'mysqldb:admin'
  master_db: 'mysqldb:master'
  second_sb: 'mysqldb:second'
```
