### ISSUE TITLE
CLI doesn't handle our custom YAML tags

### ISSUE THREAD

**Issue by Crell** [platformsh/platformsh-cli#700]
The following `.platform.app.yaml` fragment:

```
hooks:
    build: !include
        type: string
        path: '.platform/hooks/build.sh'
    deploy: !include
        type: string
        path: '.platform/hooks/deploy.sh'
```

Yields this error:

`Tags support is not enabled. You must use the flag `Yaml::PARSE_CUSTOM_TAGS` to use "!include" at line 29 (near "!include").`
