### ISSUE TITLE
Option to generate my drush aliases in ./drush/sites/self.site.yml

### ISSUE THREAD

**Issue by simesy** [platformsh/platformsh-cli#734]
Drush 9 defaults to --local, which means that drush will normally only discover aliases and command files within the current codebase. Drush won't auto-discover global aliases and command files.

The Platform CLI however, when generating aliases, assumes that aliases should go in `~/.drush`, and it also generates a `~/.drush/drush.yml` (overwriting what is already there).

This is frustrating to me as I try to build well defined codebases that other developers will readily adopt, but running `platform local:drush-aliases` on one project effects the aliases on another project.

So at the very least can the CLI please not auto-generate `drush.yml`, or at least ask the user.

Thinking bigger picture, it would be great if I could use the CLI to generate aliases in `./drush/sites/self.site.yml` of the current site. This would give me very clean aliases like `drush @master status` (where `master` is the branch name of the remote instance).

As an example, I currently maintain a self.site.yml in each project I do. This is what my `./drush/sites/self.site.yml` looks like on a typical Platform.sh project. 

```
vm:
  host: lilengine.vm
  options:
    alias-path: /var/www/drupalvm/docroot/drush
    local: true
  root: /var/www/drupalvm/web
  uri: lilengine.vm
  user: vagrant
  ssh:
    options: .... ... 
master:
  host: ssh.au.platform.sh
  user: abc123abc123-master-7rqtwti--app
  platformsh-cli-auto-remove: true
  uri: 'https://www.lilengine.co/'
  root: /app/web
develop:
  host: ssh.au.platform.sh
  user: abc123abc123-develop-sr3snxi--app
  platformsh-cli-auto-remove: true
  uri: 'https://develop-sr3snxi-qhb4ajd4xefx6.au.platformsh.site/'
  root: /app/web
```

It would great to be able to auto-update that file based on current Platform instances.
