### ISSUE TITLE
Unknown section checks in app config file

### ISSUE THREAD

**Issue by mcyprian** [platformsh/platformsh-cli#747]
I have a simple config file like this:
```
name: app 
type: "python:3.7"

dependecies:
    python:
       pipenv: '*' 

hooks:
    build: |
      pipenv install --system

disk: 1024

web:
    commands:
        start: python server.py
```
CLI currently checks if the required fields (_name_, _type_ and _disk_) are present. In case there is some extra non existing section like _dependecies_ with missing n letter it is not detected and the build simply fails during the build hook. Similar typos and mistakes are easy to make, but hard to debug. Could be some additional logic added to prevent issues like this one?
